services:
  api:
    build: .
    container_name: docflow-api
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: docflow-postgres
    environment:
      POSTGRES_USER: docflow_user
      POSTGRES_PASSWORD: docflow_password
      POSTGRES_DB: docflow_db
    ports:
      - "5433:5432"
