"""add document error fields

Revision ID: e503468f41f0
Revises: 737e67b8a574
Create Date: 2026-08-21 07:29:15.854945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e503468f41f0'
down_revision: Union[str, Sequence[str], None] = '737e67b8a574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('error_message', sa.String(length=1000), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'error_message')
    # ### end Alembic commands ###
